apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ws-server
  labels:
    app: ws-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ws-server
  serviceName: 'ws-server-headless-service'
  template:
    metadata:
      labels:
        app: ws-server
    spec:
      containers:
        - name: ws-server-container
          image: adamviktora/ws-server:latest
          ports:
            - containerPort: 3000
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: KAFKA_USERNAME
              value: 'user1'
            - name: KAFKA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-user-passwords
                  key: client-passwords
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
          lifecycle:
            preStop:
              exec:
                command: ['node', '/usr/src/app/dist/cleanup.js']
---
apiVersion: v1
kind: Service
metadata:
  name: ws-server-service
spec:
  type: NodePort
  selector:
    app: ws-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30300
---
apiVersion: v1
kind: Service
metadata:
  name: ws-server-headless-service
spec:
  clusterIP: None
  selector:
    app: ws-server
